USE `spdms_lab`;

-- Schema DDL for table `activities`
DROP TABLE IF EXISTS `activities`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE `activities` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `category_id` bigint DEFAULT NULL,
  `stage_id` bigint DEFAULT NULL,
  `activity_name` varchar(255) NOT NULL,
  `activity_description` text,
  `mode_type` varchar(50) NOT NULL,
  `frequency` varchar(100) DEFAULT NULL,
  `max_points` int NOT NULL,
  `xp` varchar(100) DEFAULT NULL,
  `cap` varchar(100) DEFAULT NULL,
  `is_mandatory` tinyint(1) NOT NULL DEFAULT '0',
  `evidence_required` tinyint(1) NOT NULL DEFAULT '1',
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `category` varchar(50) DEFAULT NULL,
  `description` text,
  `evidence` varchar(255) DEFAULT NULL,
  `justification` text,
  `name` varchar(255) NOT NULL,
  `owner_department` varchar(100) DEFAULT NULL,
  `owner_subrole` varchar(100) DEFAULT NULL,
  `type` varchar(50) DEFAULT NULL,
  `xp_category` varchar(100) DEFAULT NULL,
  `subgroup_id` bigint NOT NULL,
  `department_id` varchar(50) DEFAULT NULL,
  `teacher_id` varchar(50) DEFAULT NULL,
  `display_order` int NOT NULL,
  `maximum_awards` int DEFAULT NULL,
  `status` varchar(50) NOT NULL,
  `award_type` varchar(50) NOT NULL,
  `award_xp` int NOT NULL,
  `repeat_allowed` bit(1) NOT NULL,
  `reset_period` varchar(50) DEFAULT NULL,
  `award_days` varchar(200) DEFAULT NULL,
  `award_frequency` varchar(50) DEFAULT NULL,
  `xp_type` varchar(50) DEFAULT NULL,
  `fail_xp` int DEFAULT '0',
  `pass_xp` int DEFAULT '0',
  `award_enabled` bit(1) NOT NULL,
  `penalty_enabled` bit(1) NOT NULL,
  `penalty_xp` int NOT NULL,
  `assignment_mode` varchar(50) DEFAULT NULL,
  `subgroup` varchar(255) DEFAULT NULL,
  `allow_student_request` bit(1) DEFAULT NULL,
  `assigned_academic_year` enum('FIRST_YEAR','FOURTH_YEAR','SECOND_YEAR','THIRD_YEAR') DEFAULT NULL,
  `academic_year` enum('FIRST_YEAR','FOURTH_YEAR','SECOND_YEAR','THIRD_YEAR') DEFAULT NULL,
  `attendance_engine_enabled` bit(1) NOT NULL,
  `attendance_rule` varchar(20) DEFAULT NULL,
  `manual_evidence_name` varchar(255) DEFAULT NULL,
  `streak_enabled` bit(1) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_activity_subgroup` (`subgroup_id`,`activity_name`),
  UNIQUE KEY `uq_activity` (`category_id`,`activity_name`),
  KEY `activities_ibfk_2` (`stage_id`),
  KEY `FK7sdf72jxqeia9stse1x05o1mq` (`subgroup_id`),
  CONSTRAINT `activities_ibfk_1` FOREIGN KEY (`category_id`) REFERENCES `activity_categories` (`id`),
  CONSTRAINT `activities_ibfk_2` FOREIGN KEY (`stage_id`) REFERENCES `activity_stages` (`id`),
  CONSTRAINT `FK7sdf72jxqeia9stse1x05o1mq` FOREIGN KEY (`subgroup_id`) REFERENCES `activity_subgroups` (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=53 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
