USE `spdms_lab`;

-- Schema DDL for table `students`
DROP TABLE IF EXISTS `students`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE `students` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `full_name` varchar(100) DEFAULT NULL,
  `reg_no` varchar(50) NOT NULL,
  `spr_no` varchar(50) DEFAULT NULL,
  `department_id` bigint NOT NULL,
  `section_id` bigint DEFAULT NULL,
  `user_id` bigint DEFAULT NULL,
  `DOB` date DEFAULT NULL,
  `gender_id` bigint NOT NULL,
  `phone_no` varchar(15) NOT NULL,
  `academic_year_id` bigint NOT NULL,
  `year_id` bigint NOT NULL,
  `semester_id` bigint NOT NULL,
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `academic_year` varchar(20) DEFAULT NULL,
  `active` bit(1) NOT NULL,
  `address` varchar(255) DEFAULT NULL,
  `date_of_birth` date DEFAULT NULL,
  `email` varchar(150) NOT NULL,
  `gender` varchar(10) DEFAULT NULL,
  `password` varchar(255) NOT NULL,
  `phone` varchar(20) DEFAULT NULL,
  `score` int NOT NULL,
  `semester` varchar(20) DEFAULT NULL,
  `year` varchar(10) DEFAULT NULL,
  `current_stage` int NOT NULL,
  `stage` int DEFAULT '1',
  `total_xp` int NOT NULL,
  `team_id` bigint DEFAULT NULL,
  `group_id` bigint DEFAULT NULL,
  `section` varchar(50) DEFAULT NULL,
  `group_xp` int NOT NULL,
  `individual_xp` int NOT NULL,
  `must_xp` int NOT NULL,
  `is_captain` bit(1) NOT NULL,
  `promotion_order` int DEFAULT NULL,
  `promotion_timestamp` datetime(6) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `UKe2rndfrsx22acpq2ty1caeuyw` (`email`),
  UNIQUE KEY `reg_no` (`reg_no`),
  UNIQUE KEY `uk_reg_no` (`reg_no`),
  UNIQUE KEY `spr_no` (`spr_no`),
  KEY `fk_students_gender` (`gender_id`),
  KEY `idx_students_academic_year` (`academic_year_id`),
  KEY `idx_students_year` (`year_id`),
  KEY `idx_students_semester` (`semester_id`),
  KEY `fk_students_user` (`user_id`),
  KEY `students_ibfk_1` (`department_id`),
  KEY `fk_students_section` (`section_id`),
  KEY `FKjgyxg2x86o4me9gr70elinthr` (`team_id`),
  KEY `FKfob3k6rgxnlssnrcy55yuxfkl` (`group_id`),
  CONSTRAINT `fk_students_academic_year` FOREIGN KEY (`academic_year_id`) REFERENCES `academic_years` (`id`),
  CONSTRAINT `fk_students_gender` FOREIGN KEY (`gender_id`) REFERENCES `genders` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `fk_students_section` FOREIGN KEY (`section_id`) REFERENCES `section` (`id`),
  CONSTRAINT `fk_students_semester` FOREIGN KEY (`semester_id`) REFERENCES `semesters` (`id`),
  CONSTRAINT `fk_students_user` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`),
  CONSTRAINT `fk_students_year` FOREIGN KEY (`year_id`) REFERENCES `years` (`id`),
  CONSTRAINT `FKfob3k6rgxnlssnrcy55yuxfkl` FOREIGN KEY (`group_id`) REFERENCES `groups` (`id`),
  CONSTRAINT `FKjgyxg2x86o4me9gr70elinthr` FOREIGN KEY (`team_id`) REFERENCES `teams` (`id`),
  CONSTRAINT `students_ibfk_1` FOREIGN KEY (`department_id`) REFERENCES `departments` (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=338 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
